"""Write results/summary.md and inject it into README.md.

This exists so the results table in the README is generated, never typed. The
README carries a pair of marker comments and everything between them is
replaced on each run.
"""
import csv
from pathlib import Path

BEGIN = "<!-- BEGIN GENERATED RESULTS -->"
END = "<!-- END GENERATED RESULTS -->"
LEGACY_MARKER = "<!-- RESULTS TABLE -->"


def read_tsv(path):
    with open(path) as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


inp = snakemake.input  # noqa: F821
cfg = snakemake.config  # noqa: F821

retention = read_tsv(inp.retention)
alpha = read_tsv(inp.alpha)
alpha_tests = read_tsv(inp.alpha_tests)
permanova = read_tsv(inp.permanova)
counts = read_tsv(inp.counts)
long_counts = read_tsv(inp.long)
manifest = read_tsv(inp.samples)

sub = sum(int(r["subsampled_pairs"]) for r in retention)
post = sum(int(r["post_qc_pairs"]) for r in retention)
mapped = sum(int(r["mapped_pairs"]) for r in retention)
qc_pct = 100.0 * post / sub if sub else 0.0
map_pct = 100.0 * mapped / post if post else 0.0

groups = {}
for r in manifest:
    groups.setdefault(r["diagnosis"], []).append(r["sample_id"])


import collections

_tot = collections.Counter()
_ns = collections.Counter()
_name = {}
for _r in long_counts:
    _tot[_r["accession"]] += int(_r["reads"])
    _ns[_r["accession"]] += 1
    _name[_r["accession"]] = _r["virus"]
_total_viral = sum(_tot.values())
_top2_share = (100.0 * sum(c for _, c in _tot.most_common(2)) / _total_viral
               if _total_viral else 0.0)


def f(value, nd=3):
    try:
        return f"{float(value):.{nd}f}"
    except (TypeError, ValueError):
        return "NA"


def fp(value):
    try:
        p = float(value)
    except (TypeError, ValueError):
        return "NA"
    return f"{p:.4f}" if p >= 0.0001 else f"{p:.2e}"


lines = [BEGIN, ""]
lines.append(f"Generated by the pipeline. {len(manifest)} samples, "
             + ", ".join(f"{k} n={len(v)}" for k, v in sorted(groups.items()))
             + ".")
lines.append("")

lines.append("### Read retention")
lines.append("")
lines.append("| Step | Read pairs | Percent of previous |")
lines.append("|---|---:|---:|")
lines.append(f"| Subsampled input | {sub:,} | |")
lines.append(f"| After fastp | {post:,} | {qc_pct:.1f}% |")
lines.append(f"| Aligned to RefSeq viral | {mapped:,} | {map_pct:.4f}% |")
lines.append("")
lines.append(f"Each sample was subsampled to {cfg['subsample']['n_pairs']:,} read "
             f"pairs at seed {cfg['subsample']['seed']}. Per-sample figures are in "
             "`results/qc/read_retention.tsv`.")
lines.append("")

lines.append("### Viruses detected")
lines.append("")
lines.append(f"{len(counts)} RefSeq viral sequences passed the presence filter "
             f"(at least {cfg['presence']['min_reads']} reads across at least "
             f"{cfg['presence']['min_breadth']:.0%} of the genome) in at least one "
             f"sample.")
lines.append("")

lines.append("### What the aligned reads actually are")
lines.append("")
lines.append("| Reference | Accession | Reads | Samples |")
lines.append("|---|---|---:|---:|")
for acc, total_reads in _tot.most_common(6):
    lines.append(f"| {_name[acc]} | {acc} | {total_reads} | {_ns[acc]}/{len(manifest)} |")
lines.append("")
lines.append(f"The top two references account for {_top2_share:.0f}% of all "
             f"{_total_viral:,} aligned reads, and both are present in every sample. "
             "The first is a human endogenous retrovirus, which is host genomic "
             "sequence rather than an exogenous virus. The second carries NCBI's "
             "own UNVERIFIED_ORG flag. This is the host-contamination effect that "
             "the absence of a host-depletion step was expected to produce, and it "
             "is the most useful thing this run demonstrates.")
lines.append("")

lines.append("### Alpha diversity")
lines.append("")
lines.append("| Metric | Median, healthy | Median, periodontitis | W | p | Rank-biserial r |")
lines.append("|---|---:|---:|---:|---:|---:|")
for t in alpha_tests:
    lines.append(
        f"| {t['metric'].replace('_', ' ')} | {f(t['median_1'], 2)} | "
        f"{f(t['median_2'], 2)} | {f(t['W'], 1)} | {fp(t['p_value'])} | "
        f"{f(t['rank_biserial_r'], 2)} |"
    )
lines.append("")
lines.append("Exact two-sided Wilcoxon rank-sum tests. With 8 samples per group "
             "these have low power against anything but a large shift, which is why "
             "the effect size is reported next to the p value.")
lines.append("")

lines.append("### Beta diversity")
lines.append("")
lines.append("| Model | Term | R2 | F | p |")
lines.append("|---|---|---:|---:|---:|")
for pr in permanova:
    if not pr.get("model"):
        continue
    r2 = "" if pr.get("R2") in (None, "", "NA") else f(pr["R2"], 3)
    lines.append(f"| {pr['model']} | {pr['term']} | {r2} | {f(pr['F'], 2)} | "
                 f"{fp(pr['p_value'])} |")
lines.append("")
lines.append("Bray-Curtis on relative abundance, 9999 permutations. The "
             "betadisper row tests homogeneity of dispersion; if it is significant, "
             "a significant PERMANOVA may reflect unequal spread rather than a "
             "difference in location.")
lines.append("")
lines.append(END)

summary = "\n".join(lines) + "\n"

out_summary = Path(snakemake.output.summary)  # noqa: F821
out_summary.parent.mkdir(parents=True, exist_ok=True)
out_summary.write_text(summary)
print(f"wrote {out_summary}")

readme_path = Path(snakemake.params.readme)  # noqa: F821
text = readme_path.read_text()

if BEGIN in text and END in text:
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    text = head + summary.rstrip("\n") + tail
elif LEGACY_MARKER in text:
    text = text.replace(LEGACY_MARKER, summary.rstrip("\n"))
else:
    raise SystemExit(
        f"{readme_path} has no results markers; expected {BEGIN} ... {END}"
    )

readme_path.write_text(text)
print(f"updated {readme_path}")
